MyFace/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.user_info.urls', namespace = 'user_info')),
]

apps/user_info/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'user_info'

urlpatterns = [
    path('', views.index, name ='index'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout'),
    path('search', views.search, name='search'),
    path('search_results/<str:term>', views.search_results, name='search_results'),
    path('user_page/<int:user_id>/following_page', views.following_page, name='following_page'),
    path('add_follow/<int:following_id>', views.add_follow, name = 'add_follow'),
    path('user_page/<int:user_id>/follower_page', views.follower_page, name='follower_page'),
    path('delete_follow/<int:follow_id>', views.delete_follow, name = 'delete_follow'),
    path('user_page/<int:user_id>', views.user_page, name='user_page'),
    path('add_post', views.add_post, name='add_post'),
    path('delete_post/<int:post_id>', views.delete_post, name = 'delete_post'),
    path('add_comment', views.add_comment, name='add_comment'),
    path('user_page/<int:user_id>/photo_page', views.photo_page, name='photo_page'),
    path('add_photo', views.add_photo, name='add_photo'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/user_info/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class User(models.Model):
    email = models.EmailField(null=False, unique=True)
    username = models.CharField(max_length=128, null=True)
    password = models.CharField(max_length=128, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Follow(models.Model):
    following = models.ForeignKey(User, related_name='has_followers', on_delete=models.CASCADE)
    follower = models.ForeignKey(User, related_name='is_followings', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('following', 'follower')

class Post(models.Model):
    user = models.ForeignKey(User, related_name='has_posts', on_delete=models.CASCADE)
    target_user = models.ForeignKey(User, related_name='got_messages', on_delete=models.CASCADE, null=True)
    content = models.TextField(null=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    user = models.ForeignKey(User, related_name='has_comments', on_delete=models.CASCADE)
    content = models.TextField(null=False)
    post = models.ForeignKey(Post, related_name='has_comments', on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Photo(models.Model):
    title = models.CharField(max_length=128, null=True)
    user = models.ForeignKey(User, related_name = 'has_photos', on_delete=models.CASCADE, null=True)
    img_file = models.ImageField(upload_to='media/%Y/%m')
    profile_pic = models.IntegerField(null=True)
    

apps/user_info/views.py
from django.shortcuts import render, redirect
import apps.user_info.models as m
from django.contrib import messages
from django.db.models import Q, Count, Sum, Max

# Create your views here.
def index(request):
    if 'user_id' in request.session:
        return redirect('user_info:user_page', user_id=request.session['user_id'])

    return render(request, 'user_info/index.html')

def search(request):
    html_term = request.GET['html_term']

    if len(html_term)>0:
        return redirect('user_info:search_results', term = html_term)
    else:
        return render(request, 'user_info/search_results.html', None)

def search_results(request, term):

    results = m.User.objects.filter(Q(email__icontains = term) | Q(username__icontains=term))
    context = {
        'results': results,
    }
    return render(request, 'user_info/search_results.html', context)

def add_follow(request, following_id):

    if 'user_id' not in request.session:
        return redirect('user_info:login')

    html_user = request.session['user_id']
    html_following = following_id

    print("{} is following {}".format(html_user, html_following))
    try:
        follow = m.Follow.objects.create(follower_id = html_user, following_id = html_following)
    except:
        pass
    
    return redirect('user_info:following_page')

def delete_follow(request, follow_id):
    
    follow = m.Follow.objects.get(id = follow_id)
    follow.delete()
    
    return redirect('user_info:following_page')

def follower_page(request, user_id):

    followers = m.Follow.objects.filter(following_id = user_id).order_by('follower__username')

    context = {
        'followers': followers
    }

    return render(request, 'user_info/follower_page.html', context)

def following_page(request, user_id):

    try :
        followings = m.Follow.objects.filter(follower_id = user_id).order_by('following__username')
    except:
        followings = None

    context = {
        'followings': followings
    }

    return render(request, 'user_info/following_page.html', context)

def user_page(request, user_id):
    posts = m.Post.objects.filter(Q(user_id = user_id) | Q(target_user_id=user_id)).order_by('-updated_at')

    try:
        user = m.User.objects.get(id = user_id)
    except:
        user = None
        return redirect('user_info:index')

    context = {
        'posts': posts,
        'user': user
    }

    return render(request, 'user_info/user_page.html', context)

def add_post(request):
    if request.method == 'POST':
        html_content = request.POST['html_content']
        html_user = request.session['user_id']
        try:
            html_target = request.POST['html_target']
        except:
            html_target = None

        if len(html_content) > 0:
            post = m.Post.objects.create(user_id = html_user, content = html_content, target_user_id = html_target)

    return redirect('user_info:index')
    
def delete_post(request, post_id):
    post = m.Post.objects.get(id = post_id)
    post.delete()
    return redirect('user_info:index')

def add_comment(request):
    if request.method == 'POST':

        html_comment = request.POST['html_comment']
        html_user = request.session['user_id']
        html_post = request.POST['html_post']

        print("{} +++ {} +++ {}".format(html_comment, html_user, html_post))

        if len(html_comment) > 0:
            comment = m.Comment.objects.create(user_id = html_user, content = html_comment, post_id = html_post)
            post = m.Post.objects.get(id = html_post)
            post.save()

    return redirect('user_info:index')

def add_photo(request):
    
    if request.method == 'POST':
        html_file = request.FILES['html_file']
        html_title = request.POST['html_title']
        html_user = request.POST['html_user']

        photo = m.Photo.objects.create(img_file = html_file, title = html_title, user_id = html_user )
        return redirect('user_info:photo_page', user_id = html_user)

    return redirect('user_info:index')

def add_profile_pic(request):
    return redirect('user_info:index')

def remove_profile_pic(request):
    return redirect('user_info:index')

def photo_page(request, user_id):

    try:
        photos = m.Photo.objects.filter(user_id = user_id)
    except:
        photos = None

    try:
        profile = m.Photo.objects.get(Q(user_id=user_id) & Q(profile_pic=1))
    except:
        profile = None

    print(profile)

    context = {
        'user': m.User.objects.get(id=user_id),
        'photos': photos,
        'profile': profile,
    }

    return render(request, 'user_info/photo_page.html', context)


def login(request):
    if request.method == 'POST':
        html_email = request.POST['html_email']
        html_password = request.POST['html_password']
        try:
            user = m.User.objects.get(email = html_email)
            if user.password == html_password:
                request.session['user_id'] = user.id
                request.session['email'] = user.email
                request.session['username'] = user.username
                return redirect('user_info:index')
            else:
                messages.error(request, 'Invalid Login')
                return redirect('user_info:login')

        except:
            messages.error(request, 'No such user')
            return redirect('user_info:login')

    return render(request, 'user_info/login.html')

def logout(request):
    request.session.clear()
    return redirect('user_info:index')

def register(request):
    if 'user_id' in request.session:
        return redirect('user_info:index')

    if request.method == 'POST':
        if len(request.POST['html_password']) > 0 and request.POST['html_password']==request.POST['html_confirm']:
            try:
                user = m.User.objects.create(email = request.POST['html_email'], password = request.POST['html_password'], username = request.POST['html_username'])
                request.session['user_id'] = user.id
                request.session['email'] = user.email
                request.session['username']=user.username
            except:
                messages.error(request, 'This is wrong')
                return redirect('user_info:register')

        return redirect('user_info:index')

    return render(request, 'user_info/register.html')

apps/user_info/templates/user_info/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'user_info/lib/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'user_info/css/style.css' %}">
    <title>MyFace</title>
</head>
<body>
    {% include 'user_info/navbar.html' %}
    
    {% block body %}

    {% endblock %}
    </div>
    <script src="{% static 'user_info/lib/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'user_info/lib/popper.min.js' %}"></script>
    <script src="{% static 'user_info/lib/bootstrap.min.js' %}"></script>
    
</body>
</html>

apps/user_info/templates/user_info/errors.html
{% if messages %}
{% for message in messages %}
<div class="alert alert-danger">{{message}}</div>
{% endfor %}
{% endif %}

apps/user_info/templates/user_info/follower_page.html
{% extends 'user_info/base.html' %}

{% block body %}

{% if followers %}
<h1>You have followers ... </h1>
<div class="container">
    {% for follower in followers %}
    <div class="row border col-8">
        <div class="col-4">
            <a href="{% url 'user_info:user_page' user_id=follower.follower.id %}">
            {{follower.follower.username}}
            </a>
        </div>

        <a href="">Unfollow</a>
    </div>
        
    {% endfor %}
</div>

{% else %}
<h1>No Followers</h1>

{% endif %}
{% endblock %}

apps/user_info/templates/user_info/following_page.html
{% extends 'user_info/base.html' %}

{% block body %}

{% if followings %}
<h1>You are following ... </h1>
<div class="container">
    {% for following in followings %}
    <div class="row border col-8">
        <div class="col-4">
            {{following.following.username}}
        </div>
        <div class="col-4">

        </div>
        <a href="{% url 'user_info:delete_follow' follow_id=following.id %}" class="btn btn-primary">Unfollow</a>
    </div>
        
    {% endfor %}
</div>

{% else %}
<h1>No Followings</h1>

{% endif %}
{% endblock %}

apps/user_info/templates/user_info/index.html
{% extends 'user_info/base.html' %}

{% block body %}

<div class="jumbotron jumbotron-fluid index-bg">
        <div class="container col-md-6 offset-md-3">
            <h1 class="display-4 text-center">Hello, Where do you want to go?</h1>
        
        </div>
    </div>
    
{% endblock %}

apps/user_info/templates/user_info/login.html
{% extends 'user_info/base.html' %}

{% block body %}

<div class="jumbotron jumbotron-fluid login-bg">
        <div class="container">
        <h1 class="display-4 text-center"> Login ...</h1>

{% include 'user_info/loginform.html' %}

{% include 'user_info/errors.html' %}

</div>

{% endblock %}

apps/user_info/templates/user_info/loginform.html
<div class="row my-5">
        <div class="col-6 offset-3">
            <form action="{% url 'user_info:login' %}" method="POST">
                {% csrf_token %}
                 <div class="form-group">
                     <input type="text" class="form-control" name="html_email" id="" placeholder="email">
                 </div>
                 <div class="form-group">
                     <input type="password" class="form-control"  name="html_password" id="" placeholder="password">
                 </div>
                 <button class="btn btn-primary">Login</button>
             </form>
        </div>
    </div>

apps/user_info/templates/user_info/navbar.html
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">

        <div class="container">
    
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'user_info:index' %}"><b>MyFace</b> <span class="sr-only">(current)</span></a>
            </li>
            <form class="form-inline mx-3" action="{% url 'user_info:search' %}">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" name="html_term">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>
          </ul>

          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              {% if request.session.user_id %}
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ request.session.username }}
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'user_info:user_page' user_id=request.session.user_id %}">Edit Profile</a>
                    <a class="dropdown-item" href="{% url 'user_info:logout' %}">Logout</a>
                  </div>
              
              {% else %}
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Account
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'user_info:login' %}">Login</a>
                <a class="dropdown-item" href="{% url 'user_info:register' %}">Register</a>
              </div>
              {% endif %}
            </li>
            </div>
          
          </ul>
    
        </div>
        </div>
    </nav>

apps/user_info/templates/user_info/photo_page.html
{% extends 'user_info/base.html' %}

{% block body %}

<div class="wrapper row">

<nav id="sidebar" class='col-2'>
    <ul>
        <li class="active nav-item">{{user.username}}</li>
        <img class="img-rounded profile-pic" src="{{profile.img_file.url}}" alt="">
        <li><a href="{% url 'user_info:follower_page' user_id=user.id %}">Follower</a></li>
        <li><a href="{% url 'user_info:following_page' user_id=user.id %}">Following</a></li>
        <li><a href="{% url 'user_info:photo_page' user_id=user.id %}">Photos</a></li>
    </ul>
</nav>

<div class="col-8">
{% if request.session.user_id %}
    {% if request.session.user_id == user.id %}

    <form action="{% url 'user_info:add_photo' %}" enctype="multipart/form-data" method="POST" class="my-2">
        {% csrf_token %}
        <div class="input-group mb-3">
          <input type="file" class="form-control" placeholder="" aria-label="" name="html_file" aria-describedby="basic-addon1">
        </div>
        <div>
            <input type="text" class="form-control" name="html_title">
            <input type="hidden" name="html_user" value="{{user.id}}">
        </div>
        <button class="btn btn-primary" type="submit">Upload</button>
    </form>

    <hr>

    {% else %}

    <div>
        User Photos:
    </div>
    <hr>
    
    {% endif %}

    <div class="row">
        {% for photo in photos %}
        <div class="col-3">
            <img class="img-rounded show-photo" src="{{photo.img_file.url}}" alt="">
            <div class="small">
                {{photo.title}}
            </div>
        </div>
        
        {% endfor %}
    </div>

{% endif %}
</div>

</div>
{% endblock %}

apps/user_info/templates/user_info/register.html
{% extends 'user_info/base.html' %}

{% block body %}

<div class="jumbotron jumbotron-fluid register-bg">
        <div class="container">
        <h1 class="display-4 text-center"> Register and Create a new account...</h1>

{% include 'user_info/registerform.html' %}

{% include 'user_info/errors.html' %}
</div>

{% endblock %}

apps/user_info/templates/user_info/registerform.html
<div class="container">
<div class="row my-5">
    <div class="col-6 offset-3">
        <form action="{% url 'user_info:register' %}" method='POST'>
            {% csrf_token %}
            <div class="form-group">
                <input type="text" name="html_email" id="" placeholder="email" class="form-control">
            </div>
            <div class="form-group">
                <input type="text" name="html_username" id="" placeholder="user name" class="form-control">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="html_password" id="" placeholder="password">
            </div>
            
            
            <div class="form-group">
                <input type="password" class="form-control" name="html_confirm" id="" placeholder="confirm password">
            </div>

            <button class="btn btn-primary" role="submit">Register</button>
            
            <div class="form-check">
                <input type="checkbox" class="form-check-label" id="remember" name="html_remember">
                <label class="form-check-label" for="remember">Remember Me</label>
            </div>

        </div>
        </form>
    </div>

</div>
</div>

apps/user_info/templates/user_info/search_results.html
{% extends 'user_info/base.html' %} 

{% block body %}

{% if results %}
<h1>Results ... </h1>
<div class="container">
    {% for result in results %}
    <div class="row border col-8">
        <div class="col-4">
            <a href="{% url 'user_info:user_page' user_id=result.id %}">
            {{result.username}}
            </a>
        </div>
        <div class="col-4">
            {{result.email }}
        </div>

        <a href="{% url 'user_info:add_follow' following_id=result.id %}" class="btn btn-primary">Follow</a>
    </div>
        
    {% endfor %}
</div>

{% else %}
<h1>No Results</h1>

{% endif %}

{% endblock %}

apps/user_info/templates/user_info/user_page.html
{% extends 'user_info/base.html' %}

{% block body %}

<div class="wrapper">
    <nav id="sidebar">
        <ul>
            <li class="active nav-item">{{user.username}}</li>
            <li><a href="">Follower</a></li>
            <li><a href="">Following</a></li>
            <li><a href="{% url 'user_info:photo_page' user_id=user.id %}">Photos</a></li>
        </ul>
    </nav>

<div class="container pr-5">
{% if request.session.user_id %}
    {% if request.session.user_id == user.id %}

    <form action="{% url 'user_info:add_post' %}" method="POST" class="my-2">
        {% csrf_token %}
        <div class="form-group">
            <label>Posting Something ... </label>
            <textarea class="form-control" rows="3" name="html_content"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Post it</button>
    </form>

    <hr>
    {% else %}
    <form action="{% url 'user_info:add_post' %}" method="POST" class="my-2">
        {% csrf_token %}
        <div class="form-group">
            <label>Post Something to {{user.username}}... </label>
            <input type="hidden" name="html_target" value="{{user.id}}">
            <textarea class="form-control" rows="3" name="html_content"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Post it</button>
    </form>

    <hr>
    {% endif %}

{% endif %}


<div class="container">
{% for post in posts %}
    <div class="rounded col-8 bg-secondary my-3">
        <div class="bg-info">
        {% if post.target_user %}
            {{post.user.username}} > {{post.target_user.username}}

        {% else %}
            {{post.user.username}}
        
        {% endif %}
        </div>

        <div class="font-weight-bold lead">{{post.content}}</div>


        <div class="row border border-dark border-top border-right-0 border-left-0 small">
            {% if post.user.id == request.session.user_id %}
            <a class="text-danger text-left col-6" href="{% url 'user_info:delete_post' post_id=post.id %}">delete</a>
            <div class="col-6 text-right">{{post.updated_at}}</div>
            {% else %}
            <div class="col-12 text-right">{{post.updated_at}}</div>
            {% endif %}
        </div>

        {% for comment in post.has_comments.all %}
        <div>
            <div>
                {{comment.content}}
            </div>

            <div>
                by {{comment.user.username}} at {{comment.created_at}}
            </div>
        </div>
        

        {% empty %}

        {% endfor %}
        <form action="{% url 'user_info:add_comment' %}" method="POST" class="my-2">
            {% csrf_token %}
            <div class="form-group">
                <input type="hidden" name="html_post" value="{{post.id}}">
                <input type="text" class="form-control" rows="1" name="html_comment">
            </div>
            <button type="submit" class="btn btn-primary">Comment</button>
        </form>
        
      </div>
{% endfor %}
</div>

</div>
</div>
{% endblock %}